### ISSUE TITLE
"send to txt2img" and "send to img2img" buttons don't work

### ISSUE THREAD

**Issue by shawn-j** [fkunn1326/openpose-editor#102]
when I press either of those buttons, it switches to the right tab, but doesn't put the pose into controlnet.  there are no errors, nothing in the CLI window about it either.

**Comment by fkunn1326** [comment]
Fixed in https://github.com/fkunn1326/openpose-editor/commit/8f17b06495ea790e16def374a6eb151e0fb29c6f

**Comment by gohan2091** [comment]
I am having the same issue. I am using SD.Next (Vlads A1111). Any idea?
