### ISSUE TITLE
Pose ignored

### ISSUE THREAD

**Issue by system1system2** [fkunn1326/openpose-editor#12]
Hi. Thanks for sharing this project with the community. 

I tried the editor but I must be doing something wrong:

1. I start the OpenPose Editor and arrange the pose I like.
2. I save `pose.png`
3. I go to the img2img tab and load `pose.png` to both the img2img upload area and the ControlNet upload area.
4. I set `Denoising Strength` to 1 in the img2img settings
5. I enable ControlNet and select `openpose` as Preprocessor and `control_sd15_openpose [fef5e48e]` as model.
6. I select `v1-5-pruned-emaonly.ckpt [cc6cb27103]` as my Stable Diffusion model.

The images generated are both incredibly dark or black and the pose is completely ignored, no matter the prompt I use.

So I thought "OK, that's correct because the input image is a black canvas with the pose."
But then, I get the same results if I load `pose.png` in the ControlNet section of txt2img tab. 

What am I doing wrong?

**Comment by jparmstr** [comment]
No Preprocessor should be selected

**Comment by FlashlightET** [comment]
![image](https://user-images.githubusercontent.com/29938499/220429882-6f3c47e6-b5d2-4865-9b0f-a9bf52499a8d.png)
its ignoring my pose but i have everything set correctly
