### ISSUE TITLE
openpose_editor_index 404

### ISSUE THREAD

**Issue by vndroid** [fkunn1326/openpose-editor#129]
**Describe the bug**
Chrome report 404 error, the path `https://my_stable_diffusion_domain/openpose_editor_index` 

```json
{"detail":"Not Found"}
```

**To Reproduce**

After installation, only.

**Expected behavior**

**Screenshots**
![1690177141403](https://github.com/fkunn1326/openpose-editor/assets/15273693/68ff1cd7-e692-490a-86f8-1ae7818489a2)

**Environment**
 - OS: [e.g. iOS] Windows (Server on Linux x64)
 - Browser [e.g. chrome, safari] Chrome

**Additional context**

**Comment by huchenlei** [comment]
See https://github.com/fkunn1326/openpose-editor/issues/127. Wrong repository.
