### ISSUE TITLE
Txt2Img renders a skeleton and not an image posed as the sekelton

### ISSUE THREAD

**Issue by joetech** [fkunn1326/openpose-editor#14]
In my case, I have two skeletons (but have tried with just one).  I post them and then hit the `Send to ControlNet` button.  That sends my skeleton into the `ControlNet` section of the `Txt2Img` tab.  I check that ControlNet is enabled and `canny` is selected for the preprocessor and model.  The result is the skeleton with some shading and color.  My prompt is "a photo of two men fighting"

![image](https://user-images.githubusercontent.com/1650878/219974509-ba7dde81-fb23-40d7-80fe-3138671625b7.png)

**Comment by jparmstr** [comment]
You should not be using any Preprocessor for this. Select Preprocessor = none and Control Net should detect the skeletons as poses.

**Comment by joetech** [comment]
> You should not be using any Preprocessor for this. Select Preprocessor = none and Control Net should detect the skeletons as poses. Also the model should be Open Pose.

Perfect.  Thank you!  I'll close this as it was user error.
