### ISSUE TITLE
Colors of body lines are reversed

### ISSUE THREAD

**Issue by jparmstr** [fkunn1326/openpose-editor#15]
Referring to [this image](https://raw.githubusercontent.com/CMU-Perceptual-Computing-Lab/openpose/master/.github/media/keypoints_pose_18.png) which shows a figure facing the camera, your body line colors are horizontally reversed from what they should be. The head is correct as is.

![pose](https://user-images.githubusercontent.com/33569918/219977214-552e342c-ed18-46f8-aa97-36f6089b35b4.png)
![keypoints_pose_18](https://user-images.githubusercontent.com/33569918/219977222-f734cdb1-955b-440a-855f-432dc5cadc6a.png)

**Comment by fkunn1326** [comment]
Fixed in a1914d1
