### ISSUE TITLE
Feature request: Rotate

### ISSUE THREAD

**Issue by morganavr** [fkunn1326/openpose-editor#25]
Currently only Scale and Move operations are working.

**Comment by mykeehu** [comment]
And please add simple horizontal/vertical flip too!

**Comment by wmooring** [comment]
It seems like you're *supposed* to be able to rotate by dragging a box around everything, holding down the Alt key and clicking and dragging on one of the horizontal or vertical control points, but currently it just seems to break everything.

**Comment by ian23722** [comment]
[add_rotate_support.patch](https://github.com/fkunn1326/openpose-editor/files/10915180/add_rotate_support.patch)

Here's a diff that will add rotation and also makes top/left to the center of circles/lines.

I hope this will be added to the mainline. In case anyone really wants it, download the patch file I attached and run
`git apply add_rotate_support.patch`

**Comment by ian23722** [comment]
[rotate_and_flip.patch](https://github.com/fkunn1326/openpose-editor/files/10915519/rotate_and_flip.patch)

this will fix the flip issue as well. you can rotate, flip and move. One downside is there's like occasional 100-300ms delay. Not sure where it comes from. To apply this, `git apply rotate_and_flip.patch`. Hope the project owner has a chance to look at this commit.

**Comment by wmooring** [comment]
I would love it if that patch got added, isn't that supposed to be done as a [Pull Request](https://github.com/fkunn1326/openpose-editor/pulls), though?
