### ISSUE TITLE
Inpaint compatibility?

### ISSUE THREAD

**Issue by Rb-diff** [fkunn1326/openpose-editor#28]
First of all I have to say I have been enjoying this extension greatly. I just wonder (as a non-coder) if it would be possible to make it compatible with inpaint models. 

Currenty you get a channel expectation error if you try and the workaround is extremely tedious and time consuming.

If such a feature isn't possible it would be nice to hear as to not get my hopes up needlessly.

Thank you in advance-

**Comment by fkunn1326** [comment]
I'm not a ControlNet developer so I can't answer your question, but
That's being planned according to this discussion https://github.com/lllyasviel/ControlNet/discussions/30
