### ISSUE TITLE
Feature request: is it possible to add hand 

### ISSUE THREAD

**Issue by camenduru** [fkunn1326/openpose-editor#31]
https://twitter.com/Artoid_XYZ/status/1627670405849960448

![FpalanbaAAAPFOp](https://user-images.githubusercontent.com/54370274/220156467-afd3355f-5baf-4113-b25f-fe8b47516c19.png)

**Comment by TS9001** [comment]
1+ This would be a "killer" feature, strongly improving the usability of the editor.

**Comment by bonzianimarazzi** [comment]
it would be very useful

**Comment by yamasoo** [comment]
Or you can add some hand depth maps
