### ISSUE TITLE
skeleton windown dont showing

### ISSUE THREAD

**Issue by Gargantuanman** [fkunn1326/openpose-editor#33]
Hello i have just installed open pose, 
im on Commit hash: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8
I have updated pip and pytorch 
i have tried 3 times but always in open pose editor tab  the screen where skelleton should appear is blank, just a white border and nothing inside, i have disbale ad blocker, disable and enable GPU accel, but i dont know if this have any to do with the last Automatic Commits. 

inspector shows may warnings and this error:

Uncaught SyntaxError: Identifier 'executed' has already been declared (at main.js?1676926043.611049:1:1)

thank you.

**Comment by Gargantuanman** [comment]
Buttons dont do anything and on inspector show this:

Uncaught (in promise) ReferenceError: savePNG is not defined
    at eval (eval at <anonymous> (index.4395ab38.js:75:2081), <anonymous>:3:14)
    at index.4395ab38.js:34:32410
    at HTMLButtonElement.<anonymous> (index.4395ab38.js:76:2455)
    at index.4395ab38.js:4:1266
    at Array.forEach (<anonymous>)
    at HTMLButtonElement.le (index.4395ab38.js:4:1253)
    at HTMLButtonElement._ (Button.svelte:10:48)
    at index.4395ab38.js:4:1266
    at Array.forEach (<anonymous>)
    at HTMLButtonElement.le (index.4395ab38.js:4:1253)

**Comment by fkunn1326** [comment]
Thanks for the report.
However, I cannot reproduce it in my environment, so please check the following

- other installed extensions
- startup flag
- Boot environment (colab, etc.)

**Comment by Gargantuanman** [comment]
Hello thank you seems like another extension is producing the issue, after disabling all of them worked.

The ones i had were:

ABG_extension
kohya-sd-scripts-webui
Hypernetwork-MonkeyPatch-Extension
sd-webui-additional-networks

so one of them caused the problem,if I discover which i will post in here.

**Comment by fkunn1326** [comment]
Thank you for your reply. I found that the variable called executed overlapped with kohya-sd-scripts-webui.
https://github.com/ddPn08/kohya-sd-scripts-webui/blob/main/script.js#L7
I will fix it later
