### ISSUE TITLE
ページが応答しない / Page hangs a lot

### ISSUE THREAD

**Issue by Photosounder** [fkunn1326/openpose-editor#4]
The page is reported by Chrome as being unresponsive, usually after moving some dots, and I have to wait a lot time until it stops being frozen so I can move points again or do anything. This is very inconvenient. Now the page just crashed with `Error code: Out of Memory`, maybe you have a memory leak in there.

**Comment by fkunn1326** [comment]
Thank you for your report.
I'll do some more research on memory leaks.
