### ISSUE TITLE
No "Send to ControlNet" option

### ISSUE THREAD

**Issue by ATMT88** [fkunn1326/openpose-editor#40]
**Describe the bug**
Hello guys, there is no  "Send to ControlNet" option on my PC when openpose editor is installed.
Then I "send to img2img" to generate some picture, but it seems the pose is not loaded.

**Screenshots**
<img width="861" alt="1677210618508" src="https://user-images.githubusercontent.com/6720390/221087648-3c50ff1e-7ff7-40fb-83a1-fa93ea7bb338.png">

<img width="613" alt="1677210836723" src="https://user-images.githubusercontent.com/6720390/221087963-ed4b37d2-3b5b-461c-b997-6a6e1e763fd8.png">

**Environment**
 - windows

**Comment by AZE38** [comment]
how you resolve your issue?
