### ISSUE TITLE
nothing is sent when clicking "send to txt2img" or "sent to img2img'

### ISSUE THREAD

**Issue by ananosleep** [fkunn1326/openpose-editor#42]
**To Reproduce**
1. Go to 'openpose editor'
2. Click on 'send to txt2img'
3. It automatically goes to the txt2img tab, but found nothing in ControlNet
send to img2img has the same bug

**Expected behavior**
the openpose image is sent to the tab

**Environment**
 - OS: windows
 - Browser: Microsoft Edge

**Comment by ecureuilfourbe** [comment]
try to check for update in the extension tab, it solve the issue for me

**Comment by Raivshard** [comment]
I have the same issue and checking for updates does nothing because it's the latest version

**Comment by Absalonius** [comment]
Same behavior here, on sd-webui-controlnet (c16489c0 ) and openpose-editor (2536f09a ) on python: 3.10.6  •  torch: 1.13.1+cu117  •  xformers: 0.0.16rc425  •  gradio: 3.16.2  •  commit: [0cc0ee1b](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8)

it looks like it's processing, image shows up in the controlnet section,  but the outputdoesn't adhere to pose and the pose image that gets included with output is blank.

**Comment by fkunn1326** [comment]
@Absalonius  For this extension to work, you must set preprocessor to none and use the openpose model. are you doing them?

**Comment by Rieckor** [comment]
@ananosleep I have the same issue because of the language package, you can remove it.

**Comment by ananosleep** [comment]
> @ananosleep I have the same issue because of the language package, you can remove it.

Thanks, it really works even if I don't know how language package could affect it.

**Comment by Rieckor** [comment]
感谢您的来信，我将尽快将予以回复！

**Comment by jinwenwei123** [comment]
我也遇到了同样的问题，使用中文语言包将导致发送图片到txt2img失效

**Comment by AlekPet** [comment]
In path **_\stable-diffusion-webui\extensions\openpose-editor\javascript_**
file _**main.js**_  code is looking for ControlNet panels (label contain ControlNet + selectedIndex or selectedIndex ==0 ...), in new version ControlNet panels only one and added buttons for panel selection ControlNet.
 
**Replace this code:**
```
	    gradioApp().querySelector(selector).querySelectorAll("span.transition").forEach((elem) => {
            const label = elem.previousElementSibling.textContent

            if ((label === `ControlNet - ${target_controlnet_index}`)
                    || ((target_controlnet_index === 0) && (label === "ControlNet"))) {
                elem.className.includes("rotate-90") && elem.parentElement.click();
                const input = elem.parentElement.parentElement.querySelector("input[type='file']");
                const button = elem.parentElement.parentElement.querySelector("button[aria-label='Clear']")
                button && button.click();
                input.value = "";
                input.files = list;
                const event = new Event('change', { 'bubbles': true, "composed": true });
                input.dispatchEvent(event);
            }
        })
```
**This codes:**
```
		const elem = gradioApp().querySelector(selector).querySelectorAll("span.transition")[0]
		const label = elem.previousElementSibling.textContent

		if (label === "ControlNet") {
                    elem.className.includes("rotate-90") && elem.parentElement.click();
				
		    const buttons = elem.parentElement.parentElement.children[1].querySelectorAll('button:not(button[id*="component"])')
		    buttons[target_controlnet_index].click()
				
		    const panelControlnet =  buttons[0].parentElement.parentElement.children[1+target_controlnet_index]				
                    const input = panelControlnet.querySelector("input[type='file']");
                    const button = panelControlnet.querySelector("button[aria-label='Clear']")
                    button && button.click();
                    input.value = "";
                    input.files = list;
                    const event = new Event('change', { 'bubbles': true, "composed": true });
                    input.dispatchEvent(event);
            }
```
