### ISSUE TITLE
オブジェクトオブジェクトのスケルトンのみを追加できますか?

### ISSUE THREAD

**Issue by znhacker** [fkunn1326/openpose-editor#5]
オブジェクトオブジェクトのスケルトンのみを追加できますか?

**Comment by fkunn1326** [comment]
オブジェクトオブジェクトとは何ですか？

**Comment by znhacker** [comment]
つまり、1種類のオブジェクトのみにボーンを追加することは可能ですか、それとも複数のオブジェクトのボーンを追加することは可能ですか?   感謝する~！

**Comment by fkunn1326** [comment]
すみません、あなたの言っていることがよくわかりません
具体例を示していただけますか？

**Comment by znhacker** [comment]
![mmexport1676804673522](https://user-images.githubusercontent.com/14341380/219944025-4f8f594f-0267-4555-9981-c0b9146d2e9c.jpg)

例えば、この絵に複数のフィギュアや動物まで入っていたら、動物の骨はダメな気がするし、フィギュアが増えてもダメな気がする？

**Comment by fkunn1326** [comment]
あーなるほど、たしかにそうですよね。
ただ、ControlnetでのOpenpose自体が人間以外にあまり向いていなかったりすると思います

**Comment by znhacker** [comment]
> あーなるほど、たしかにそうですよね。 ただ、ControlnetでのOpenpose自体が人間以外にあまり向いていなかったりすると思います

さて、さまざまな種類の生き物のポーズを認識するためには、別の解決策を考えなければならないようです。 回答ありがとうございました〜。
