### ISSUE TITLE
send to txt2img doesn't work When I use the Chinese language pack

### ISSUE THREAD

**Issue by zuiaiyutu** [fkunn1326/openpose-editor#53]
send to txt2img doesn't work When I use the Chinese language pack
When I use English, it works.
https://github.com/dtlnor/stable-diffusion-webui-localization-zh_CN
当我使用中文语言包的时候，发送到文生图不起作用
当我把语言切换到英语时，又正常了。

**Comment by passing11** [comment]
> send to txt2img doesn't work When I use the Chinese language pack When I use English, it works. https://github.com/dtlnor/stable-diffusion-webui-localization-zh_CN 当我使用中文语言包的时候，发送到文生图不起作用 当我把语言切换到英语时，又正常了。

可能是中文语言包的问题，我换成老版本的就好了

**Comment by AlekPet** [comment]
> send to txt2img doesn't work When I use the Chinese language pack When I use English, it works. https://github.com/dtlnor/stable-diffusion-webui-localization-zh_CN 当我使用中文语言包的时候，发送到文生图不起作用 当我把语言切换到英语时，又正常了。
See if it helps
https://github.com/fkunn1326/openpose-editor/issues/42#issuecomment-1448318445

**Comment by zuiaiyutu** [comment]
修复了，It's working fine now
