### ISSUE TITLE
[Bug] Incorrect Position of Nodes when Manipulating Flipped Pose 

### ISSUE THREAD

**Issue by 050644zf** [fkunn1326/openpose-editor#65]
**Describe the bug**
Sometimes we want flipped pose when the back of body is heading to viewer. However, when trying to flip the body, the node position stays unflipped while the lines between nodes behave correctly. 

**To Reproduce**
1. Generate a normal pose
![image](https://user-images.githubusercontent.com/30611816/223044422-bfbc5d39-0969-489f-9157-22586102f982.png)
2. drag the handle to horizontally flip the pose. you can see the nodes stay unflipped, but the lines position are correct.
![image](https://user-images.githubusercontent.com/30611816/223044704-bbe21669-2f8d-4b8a-a7c4-5da7bf7e2456.png)
3. if you trying to move the node, the lines will reconnect to the node again.
![image](https://user-images.githubusercontent.com/30611816/223045066-3cd13838-f3f4-441b-b912-3a6532838629.png)

**Expected behavior**
The node should be flipped correctly like the lines.

**Environment**
 - OS: Tested on Windows 11, Android
 - Browser: Edge, Chrome, Android Webview

**Additional context**
None

**Comment by ian23722** [comment]
https://github.com/fkunn1326/openpose-editor/issues/25
