### ISSUE TITLE
I installed the editor, but I don't see any tabs.

### ISSUE THREAD

**Issue by lgs777** [fkunn1326/openpose-editor#93]
I installed the editor, but I don't see any tabs. I get these error messages in the terminal. Please tell me how to solve it.

Error executing callback ui_tabs_callback for C:\AI\stable-diffusion-webui\extensions\openpose-editor\scripts\main.py
Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui\modules\script_callbacks.py", line 119, in ui_tabs_callback
    res += c.callback() or []
  File "C:\AI\stable-diffusion-webui\extensions\openpose-editor\scripts\main.py", line 129, in on_ui_tabs
    png_input.upload(estimate, png_input, jsonbox).then(None, jsonbox, None, _js="detectImage")
AttributeError: 'NoneType' object has no attribute 'then'

**Comment by singyanchiu** [comment]
I encountered the exact same issue after I updated. Yesterday was still working fine...

**Comment by linkksng** [comment]
I had the same issue. Workaround that works for me is to rollback to commit 42ba3d5dc132357a2ea048283efb8129ef69f8f9

**Comment by NekodRider** [comment]
Update the `stable-diffusion-webui` to the latest version will fix the problem, since there are some updates related to `gradio` update.
